# Generated by Django 3.0.14 on 2021-06-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('ELEMENTAL', 'Grado elemental'), ('MEDIO', 'Grado medio'), ('SUPERIOR', 'Grado superior'), ('ELEMENTAL-NO', 'Grado elemental (sin titulación)'), ('MEDIO-NO', 'Grado medio (sin titulación)'), ('SUPERIOR-NO', 'Grado superior (sin titulación)'), ('MASTER', 'Máster')], max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instruments.Instrument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrumentalists',
            field=models.ManyToManyField(related_name='instruments', through='instruments.InstrumentUser', to='accounts.Profile'),
        ),
    ]
