# Generated by Django 3.0.14 on 2021-05-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=200, null=True)),
                ('group', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('CURSO', 'Curso'), ('ENSEÑANZA ELEMENTAL', 'Enseñanza elemental'), ('ENSEÑANZA PROFESIONAL', 'Enseñanza profesional'), ('GRADO', 'Grado'), ('ARTISTICA', 'Artistica'), ('OTRO', 'Otro')], max_length=150)),
                ('duration', models.CharField(choices=[('0-3', '0 a 3 meses'), ('3-6', '3 a 6 meses'), ('6-1A', '6 meses a 1 año'), ('1A-2A', '1 año a 2 años'), ('2A-4A', '2 años a 4 años'), ('4A-6A', '4 años a 6 años'), ('6+', '6 años o mas')], max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
