# Generated by Django 3.0.14 on 2021-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210618_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_musician',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
