# Generated by Django 3.0.14 on 2021-05-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mails_sent', to=settings.AUTH_USER_MODEL)),
                ('parent_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mails_child', to='mails.Mail')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mails_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
