# Generated by Django 3.0.14 on 2021-05-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_sent', to='users.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_received', to='users.Profile')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
